# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  vcalculateapi:
    container_name: v-calculate-api
    image: vcalculateapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
